package liquibase.ext.redshift.snapshot;

import liquibase.Scope;
import liquibase.database.Database;
import liquibase.exception.DatabaseException;
import liquibase.executor.Executor;
import liquibase.executor.ExecutorService;
import liquibase.ext.redshift.database.RedshiftDatabase;
import liquibase.snapshot.DatabaseSnapshot;
import liquibase.snapshot.SnapshotGenerator;
import liquibase.snapshot.jvm.ColumnSnapshotGenerator;
import liquibase.statement.core.RawParameterizedSqlStatement;
import liquibase.structure.DatabaseObject;
import liquibase.structure.core.Column;

import java.util.List;
import java.util.Map;

public class RedshiftColumnSnapshotGenerator extends ColumnSnapshotGenerator {

    @Override
    public int getPriority(Class<? extends DatabaseObject> objectType, Database database) {
        if (database instanceof RedshiftDatabase) {
            return PRIORITY_DATABASE;
        }
        return PRIORITY_NONE;
    }

    @Override
    public Class<? extends SnapshotGenerator>[] replaces() {
        return new Class[] { ColumnSnapshotGenerator.class };
    }

    @Override
    protected void setAutoIncrementDetails(Column column, Database database, DatabaseSnapshot snapshot) {
        // Only process if column is marked as autoincrement and we have proper context
        if ((column.getAutoIncrementInformation() == null) ||
            (database.getConnection() == null) ||
            (column.getRelation() == null) ||
            (column.getSchema() == null)) {
            return;
        }

        try {
            // Query Redshift's pg_attrdef to get IDENTITY column details
            // adsrc format for ALWAYS: "identity(table_oid, ???, 'start,increment'::text)"
            // adsrc format for BY DEFAULT: "default_identity(table_oid, ???, 'start,increment'::text)"
            String query = "SELECT " +
                    "    SPLIT_PART(SPLIT_PART(d.adsrc, '''', 2), ',', 1)::bigint AS start_value, " +
                    "    SPLIT_PART(SPLIT_PART(d.adsrc, '''', 2), ',', 2)::bigint AS increment_by, " +
                    "    d.adsrc " +
                    "FROM pg_class c " +
                    "    JOIN pg_namespace n ON c.relnamespace = n.oid " +
                    "    JOIN pg_attribute a ON a.attrelid = c.oid " +
                    "    JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum " +
                    "WHERE c.relkind = 'r' " +
                    "    AND a.attnum > 0 " +
                    "    AND d.adsrc LIKE '%identity%' " +
                    "    AND n.nspname = ? " +
                    "    AND c.relname = ? " +
                    "    AND a.attname = ?";

            Executor executor = Scope.getCurrentScope().getSingleton(ExecutorService.class)
                    .getExecutor("jdbc", database);
            List<Map<String, ?>> rows = executor.queryForList(
                    new RawParameterizedSqlStatement(query,
                            column.getSchema().getName(),
                            column.getRelation().getName(),
                            column.getName()));

            if (!rows.isEmpty()) {
                Map<String, ?> row = rows.get(0);
                Long startValue = (Long) row.get("START_VALUE");
                Long incrementBy = (Long) row.get("INCREMENT_BY");
                String adsrc = (String) row.get("ADSRC");

                if (startValue != null && incrementBy != null && adsrc != null) {
                    Column.AutoIncrementInformation autoIncrementInfo =
                            new Column.AutoIncrementInformation(startValue, incrementBy);

                    // Detect generation type from adsrc function name
                    // "default_identity(...)" = GENERATED BY DEFAULT AS IDENTITY
                    // "identity(...)" = GENERATED ALWAYS AS IDENTITY
                    if (adsrc.startsWith("\"default_identity\"") || adsrc.startsWith("default_identity")) {
                        autoIncrementInfo.setGenerationType("BY DEFAULT");
                    } else if (adsrc.startsWith("\"identity\"") || adsrc.startsWith("identity")) {
                        autoIncrementInfo.setGenerationType("ALWAYS");
                    }

                    column.setAutoIncrementInformation(autoIncrementInfo);
                }
            }
        } catch (DatabaseException e) {
            Scope.getCurrentScope().getLog(getClass())
                    .info("Could not read Redshift IDENTITY information for column " +
                          column.getName() + ": " + e.getMessage());
        }
    }
}