CREATE TABLE test_identity_by_default(id_by_default INTEGER GENERATED BY DEFAULT AS IDENTITY (100, 5) NOT NULL)
CREATE TABLE test_identity_always(id_always INTEGER GENERATED ALWAYS AS IDENTITY (100, 5) NOT NULL)
CREATE TABLE test_identity_simple(id_simple INTEGER IDENTITY(100, 5) NOT NULL)
CREATE TABLE oleh.test_table (test_id INTEGER NOT NULL, test_column VARCHAR(50) NOT NULL, CONSTRAINT test_table_pkey PRIMARY KEY (test_id))