# This workflow will build the extension against the latest Liquibase artifact
name: "Nightly build"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
    nightly-build:
      uses: liquibase/build-logic/.github/workflows/oss-extension-test.yml@v0.5.1
      with:
        nightly: true
      secrets: inherit