name: Run Unit Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  push:
    branches:
      - main

jobs:
  unit-test:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 16]

    steps:
    - uses: actions/checkout@v2
    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Run Unit Tests With Maven
      run: mvn surefire:test --file pom.xml

  integration-tests:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    needs: unit-test
    strategy:
      matrix:
        java: [8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Test With Maven
        run: mvn clean test --file pom.xml
