name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - master
    
permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
        # write permission is required to create a github release
        contents: write
        # write permission is required for autolabeler
        # otherwise, read permission is required at least
        pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      # Drafts your next Release notes as Pull Requests are merged into the default branch
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}