name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-test:
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@v0.4.8
    secrets: inherit

  dependabot:
    uses: liquibase/build-logic/.github/workflows/dependabot-automerge.yml@v0.4.8
    secrets: inherit
  