name: Build and Test

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:

  authorize:
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  build-test:
    needs: authorize
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@main
    secrets: inherit
    with:
      extraMavenArgs: -Dtest="RedshiftDatabaseTest"

  dependabot-automerge:
    needs: build-test
    uses: liquibase/build-logic/.github/workflows/dependabot-automerge.yml@main
    secrets: inherit
